branch-defaults:
  devel:
    environment: django-env
    group_suffix: null
global:
  application_name: django-gerp
  branch: null
  default_ec2_keyname: aws-putty
  default_platform: python3.4
  default_region: eu-central-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
